import type { IChapterTableRow } from './types';

export const MOCK_CURRENT_USER_ID = 'user_1';

// Mock chapters with coin gating, unlock status, full stats
export const MOCK_CHAPTERS_TABLE: IChapterTableRow[] = [
  {
    _id: 'c1',
    slug: 'root-chapter',
    storySlug: 'the-lost-kingdom',
    parentChapterSlug: null,
    ancestorSlugs: [],
    depth: 0,
    branchIndex: 1,
    authorId: 'user_1',
    authorName: 'Dhruv M.',
    title: 'The Beginning of Everything',
    content:
      'In the land of Eldara, a young wanderer named Kael discovers a glowing rune etched into an ancient stone. The rune pulses with a warmth that speaks of forgotten power, and Kael feels an inexplicable pull to follow where it leads.',
    chapterNumber: 1,
    votes: { upvotes: 142, downvotes: 11, score: 131 },
    status: 'published',
    isEnding: false,
    pullRequest: { isPR: false },
    version: 3,
    stats: {
      reads: 4812,
      uniqueReaders: 3201,
      completionRate: 87.4,
      engagementScore: 92,
      comments: 38,
      childBranches: 3,
    },
    reportCount: 0,
    isFlagged: false,
    coinPrice: 0,
    isUnlockedByUser: true,
    createdAt: '2025-11-01T10:00:00Z',
    updatedAt: '2025-11-15T14:22:00Z',
    subRows: [
      {
        _id: 'c2',
        slug: 'child-a',
        storySlug: 'the-lost-kingdom',
        parentChapterSlug: 'root-chapter',
        ancestorSlugs: ['root-chapter'],
        depth: 1,
        branchIndex: 1,
        authorId: 'user_2',
        authorName: 'Aria K.',
        title: 'Into the Eastern Forest',
        content:
          "Kael ventures east into the Thornwood Forest, guided by the rune's faint glow. Ancient trees loom overhead, and the silence is broken only by the distant cry of an unseen creature.",
        chapterNumber: 2,
        votes: { upvotes: 87, downvotes: 5, score: 82 },
        status: 'published',
        isEnding: false,
        pullRequest: { isPR: false },
        version: 2,
        stats: {
          reads: 3104,
          uniqueReaders: 2098,
          completionRate: 79.2,
          engagementScore: 84,
          comments: 21,
          childBranches: 2,
        },
        reportCount: 0,
        isFlagged: false,
        coinPrice: 5,
        isUnlockedByUser: true,
        createdAt: '2025-11-03T12:00:00Z',
        updatedAt: '2025-11-16T09:10:00Z',
        subRows: [
          {
            _id: 'c3',
            slug: 'grandchild-a1',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-a',
            ancestorSlugs: ['root-chapter', 'child-a'],
            depth: 2,
            branchIndex: 1,
            authorId: 'user_3',
            authorName: 'Leo F.',
            title: 'The Glowing Clue',
            content:
              'Kael discovers a mysterious clue beneath an old oak tree — a shard of crystal that mirrors the rune. It shows a vision of a palace swallowed by darkness.',
            chapterNumber: 3,
            votes: { upvotes: 54, downvotes: 3, score: 51 },
            status: 'published',
            isEnding: false,
            pullRequest: { isPR: false },
            version: 1,
            stats: {
              reads: 1920,
              uniqueReaders: 1401,
              completionRate: 68.5,
              engagementScore: 71,
              comments: 9,
              childBranches: 0,
            },
            reportCount: 0,
            isFlagged: false,
            coinPrice: 10,
            isUnlockedByUser: false,
            createdAt: '2025-11-05T08:00:00Z',
            updatedAt: '2025-11-17T11:30:00Z',
          },
          {
            _id: 'c4',
            slug: 'grandchild-a2',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-a',
            ancestorSlugs: ['root-chapter', 'child-a'],
            depth: 2,
            branchIndex: 2,
            authorId: 'user_4',
            authorName: 'Nina P.',
            title: "The Stranger's Warning",
            content:
              'A cloaked figure appears from behind a willow tree, urging Kael to turn back. "The rune is a beacon," the stranger warns. "And something ancient has already seen it."',
            chapterNumber: 3,
            votes: { upvotes: 41, downvotes: 7, score: 34 },
            status: 'pending_approval',
            isEnding: false,
            pullRequest: { isPR: true, status: 'pending' },
            version: 1,
            stats: {
              reads: 980,
              uniqueReaders: 760,
              completionRate: 55.1,
              engagementScore: 58,
              comments: 14,
              childBranches: 0,
            },
            reportCount: 2,
            isFlagged: false,
            coinPrice: 0,
            isUnlockedByUser: true,
            createdAt: '2025-11-06T14:00:00Z',
            updatedAt: '2025-11-18T16:00:00Z',
          },
        ],
      },
      {
        _id: 'c5',
        slug: 'child-b',
        storySlug: 'the-lost-kingdom',
        parentChapterSlug: 'root-chapter',
        ancestorSlugs: ['root-chapter'],
        depth: 1,
        branchIndex: 2,
        authorId: 'user_5',
        authorName: 'Sam W.',
        title: 'The Deserted Village',
        content:
          'Choosing the southern road, Kael arrives at an abandoned village. The homes are intact but lifeless — as if the inhabitants vanished in an instant.',
        chapterNumber: 2,
        votes: { upvotes: 29, downvotes: 12, score: 17 },
        status: 'rejected',
        isEnding: false,
        pullRequest: { isPR: true, status: 'rejected', prId: 'pr_001' },
        version: 1,
        stats: {
          reads: 420,
          uniqueReaders: 310,
          completionRate: 42.0,
          engagementScore: 38,
          comments: 5,
          childBranches: 1,
        },
        reportCount: 3,
        isFlagged: true,
        coinPrice: 0,
        isUnlockedByUser: true,
        createdAt: '2025-11-04T09:30:00Z',
        updatedAt: '2025-11-19T12:00:00Z',
        subRows: [
          {
            _id: 'c6',
            slug: 'grandchild-b1',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-b',
            ancestorSlugs: ['root-chapter', 'child-b'],
            depth: 2,
            branchIndex: 1,
            authorId: 'user_6',
            authorName: 'Priya D.',
            title: 'The Injured Traveler',
            content:
              'Inside a ruined house, Kael finds an injured traveler clutching a tattered map. Before losing consciousness, the traveler whispers, "Follow the constellation of the Serpent."',
            chapterNumber: 3,
            votes: { upvotes: 18, downvotes: 2, score: 16 },
            status: 'published',
            isEnding: false,
            pullRequest: { isPR: false },
            version: 1,
            stats: {
              reads: 310,
              uniqueReaders: 240,
              completionRate: 61.3,
              engagementScore: 62,
              comments: 3,
              childBranches: 0,
            },
            reportCount: 0,
            isFlagged: false,
            coinPrice: 15,
            isUnlockedByUser: false,
            createdAt: '2025-11-08T11:00:00Z',
            updatedAt: '2025-11-20T08:00:00Z',
          },
        ],
      },
      {
        _id: 'c7',
        slug: 'child-c',
        storySlug: 'the-lost-kingdom',
        parentChapterSlug: 'root-chapter',
        ancestorSlugs: ['root-chapter'],
        depth: 1,
        branchIndex: 3,
        authorId: 'user_7',
        authorName: 'Zara O.',
        title: 'The Hidden Cave',
        content:
          'A narrow crevice behind a waterfall leads Kael into a vast cave system. The walls glimmer with bioluminescent moss, and the air hums with ancient energy.',
        chapterNumber: 2,
        votes: { upvotes: 103, downvotes: 4, score: 99 },
        status: 'published',
        isEnding: false,
        pullRequest: { isPR: false },
        version: 2,
        stats: {
          reads: 2760,
          uniqueReaders: 1890,
          completionRate: 83.0,
          engagementScore: 88,
          comments: 29,
          childBranches: 3,
        },
        reportCount: 0,
        isFlagged: false,
        coinPrice: 8,
        isUnlockedByUser: true,
        createdAt: '2025-11-04T16:00:00Z',
        updatedAt: '2025-11-22T10:45:00Z',
        subRows: [
          {
            _id: 'c8',
            slug: 'grandchild-c1',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-c',
            ancestorSlugs: ['root-chapter', 'child-c'],
            depth: 2,
            branchIndex: 1,
            authorId: 'user_8',
            authorName: 'Ben A.',
            title: 'Ancient Carvings',
            content:
              'Kael traces the carvings on the cave wall — a pictographic history of a civilization that once ruled the continent. One carving shows a figure holding the same rune.',
            chapterNumber: 3,
            votes: { upvotes: 12, downvotes: 4, score: 8 },
            status: 'rejected',
            isEnding: false,
            pullRequest: { isPR: true, status: 'rejected' },
            version: 1,
            stats: {
              reads: 210,
              uniqueReaders: 175,
              completionRate: 38.0,
              engagementScore: 35,
              comments: 2,
              childBranches: 0,
            },
            reportCount: 1,
            isFlagged: false,
            coinPrice: 0,
            isUnlockedByUser: true,
            createdAt: '2025-11-09T07:00:00Z',
            updatedAt: '2025-11-21T14:00:00Z',
          },
          {
            _id: 'c9',
            slug: 'grandchild-c2',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-c',
            ancestorSlugs: ['root-chapter', 'child-c'],
            depth: 2,
            branchIndex: 2,
            authorId: 'user_9',
            authorName: 'Maya R.',
            title: 'The Deep Rumble',
            content:
              'The ground shakes. A low, resonant rumble rolls through the cave as if something enormous is stirring far below. Dust cascades from the ceiling. Kael freezes.',
            chapterNumber: 3,
            votes: { upvotes: 78, downvotes: 2, score: 76 },
            status: 'published',
            isEnding: false,
            pullRequest: { isPR: false },
            version: 2,
            stats: {
              reads: 1510,
              uniqueReaders: 1100,
              completionRate: 75.4,
              engagementScore: 80,
              comments: 17,
              childBranches: 0,
            },
            reportCount: 0,
            isFlagged: false,
            coinPrice: 12,
            isUnlockedByUser: false,
            createdAt: '2025-11-10T10:00:00Z',
            updatedAt: '2025-11-23T09:00:00Z',
          },
          {
            _id: 'c10',
            slug: 'grandchild-c3',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-c',
            ancestorSlugs: ['root-chapter', 'child-c'],
            depth: 2,
            branchIndex: 3,
            authorId: 'user_1',
            authorName: 'Dhruv M.',
            title: 'Trapped in the Chamber',
            content:
              'The cave entrance collapses behind Kael, sealing him inside a vast hidden chamber. At its center, a glowing altar holds a crystal sphere that shows visions of the future.',
            chapterNumber: 3,
            votes: { upvotes: 64, downvotes: 1, score: 63 },
            status: 'pending_approval',
            isEnding: true,
            pullRequest: { isPR: true, status: 'pending' },
            version: 1,
            stats: {
              reads: 890,
              uniqueReaders: 670,
              completionRate: 90.1,
              engagementScore: 95,
              comments: 11,
              childBranches: 0,
            },
            reportCount: 0,
            isFlagged: false,
            coinPrice: 20,
            isUnlockedByUser: false,
            createdAt: '2025-11-11T15:00:00Z',
            updatedAt: '2025-11-24T11:30:00Z',
          },
        ],
      },
      {
        _id: 'c11',
        slug: 'child-d',
        storySlug: 'the-lost-kingdom',
        parentChapterSlug: 'root-chapter',
        ancestorSlugs: ['root-chapter'],
        depth: 1,
        branchIndex: 4,
        authorId: 'user_10',
        authorName: 'Rohan S.',
        title: 'The Forgotten Library',
        content:
          'Following a hidden trail beyond the mountains, Kael discovers a ruined library buried beneath centuries of dust. Strange books line the shelves, untouched by time.',
        chapterNumber: 2,
        votes: { upvotes: 94, downvotes: 6, score: 88 },
        status: 'published',
        isEnding: false,
        pullRequest: { isPR: false },
        version: 1,
        stats: {
          reads: 2450,
          uniqueReaders: 1780,
          completionRate: 81.6,
          engagementScore: 86,
          comments: 24,
          childBranches: 2,
        },
        reportCount: 0,
        isFlagged: false,
        coinPrice: 6,
        isUnlockedByUser: true,
        createdAt: '2025-11-12T10:00:00Z',
        updatedAt: '2025-11-25T08:00:00Z',
        subRows: [
          {
            _id: 'c12',
            slug: 'grandchild-d1',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-d',
            ancestorSlugs: ['root-chapter', 'child-d'],
            depth: 2,
            branchIndex: 1,
            authorId: 'user_11',
            authorName: 'Anaya T.',
            title: 'The Book of Stars',
            content:
              'One ancient manuscript reveals a map of constellations that seem to predict future events. Kael notices a symbol identical to the rune.',
            chapterNumber: 3,
            votes: { upvotes: 72, downvotes: 2, score: 70 },
            status: 'published',
            isEnding: false,
            pullRequest: { isPR: false },
            version: 1,
            stats: {
              reads: 1320,
              uniqueReaders: 990,
              completionRate: 77.8,
              engagementScore: 82,
              comments: 13,
              childBranches: 0,
            },
            reportCount: 0,
            isFlagged: false,
            coinPrice: 12,
            isUnlockedByUser: false,
            createdAt: '2025-11-13T09:00:00Z',
            updatedAt: '2025-11-26T10:00:00Z',
          },
          {
            _id: 'c13',
            slug: 'grandchild-d2',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-d',
            ancestorSlugs: ['root-chapter', 'child-d'],
            depth: 2,
            branchIndex: 2,
            authorId: 'user_12',
            authorName: 'Karan V.',
            title: 'The Librarian Spirit',
            content:
              'A spectral librarian emerges from the shadows and offers Kael a choice: knowledge of the past or a glimpse of the future.',
            chapterNumber: 3,
            votes: { upvotes: 48, downvotes: 5, score: 43 },
            status: 'pending_approval',
            isEnding: false,
            pullRequest: { isPR: true, status: 'pending' },
            version: 1,
            stats: {
              reads: 760,
              uniqueReaders: 580,
              completionRate: 66.4,
              engagementScore: 69,
              comments: 8,
              childBranches: 0,
            },
            reportCount: 1,
            isFlagged: false,
            coinPrice: 0,
            isUnlockedByUser: true,
            createdAt: '2025-11-14T12:00:00Z',
            updatedAt: '2025-11-27T15:00:00Z',
          },
        ],
      },
      {
        _id: 'c14',
        slug: 'child-e',
        storySlug: 'the-lost-kingdom',
        parentChapterSlug: 'root-chapter',
        ancestorSlugs: ['root-chapter'],
        depth: 1,
        branchIndex: 5,
        authorId: 'user_13',
        authorName: 'Meera J.',
        title: 'Across the Frozen Pass',
        content:
          'Kael travels north through a frozen mountain pass where icy winds whisper forgotten names. Strange lights flicker across the snow.',
        chapterNumber: 2,
        votes: { upvotes: 118, downvotes: 4, score: 114 },
        status: 'published',
        isEnding: false,
        pullRequest: { isPR: false },
        version: 2,
        stats: {
          reads: 3510,
          uniqueReaders: 2480,
          completionRate: 85.9,
          engagementScore: 91,
          comments: 32,
          childBranches: 1,
        },
        reportCount: 0,
        isFlagged: false,
        coinPrice: 10,
        isUnlockedByUser: true,
        createdAt: '2025-11-15T08:30:00Z',
        updatedAt: '2025-11-28T10:00:00Z',
        subRows: [
          {
            _id: 'c15',
            slug: 'grandchild-e1',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-e',
            ancestorSlugs: ['root-chapter', 'child-e'],
            depth: 2,
            branchIndex: 1,
            authorId: 'user_14',
            authorName: 'Aarav P.',
            title: 'The Ice Guardian',
            content:
              'At the summit, Kael encounters a giant guardian carved from living ice. The creature recognizes the rune and kneels before him.',
            chapterNumber: 3,
            votes: { upvotes: 97, downvotes: 1, score: 96 },
            status: 'published',
            isEnding: false,
            pullRequest: { isPR: false },
            version: 1,
            stats: {
              reads: 2100,
              uniqueReaders: 1640,
              completionRate: 88.7,
              engagementScore: 93,
              comments: 18,
              childBranches: 0,
            },
            reportCount: 0,
            isFlagged: false,
            coinPrice: 15,
            isUnlockedByUser: false,
            createdAt: '2025-11-16T09:15:00Z',
            updatedAt: '2025-11-29T13:00:00Z',
          },
        ],
      },
      {
        _id: 'c16',
        slug: 'child-f',
        storySlug: 'the-lost-kingdom',
        parentChapterSlug: 'root-chapter',
        ancestorSlugs: ['root-chapter'],
        depth: 1,
        branchIndex: 6,
        authorId: 'user_15',
        authorName: 'Aisha N.',
        title: 'The Sunken Temple',
        content:
          'Deep beneath a crystal lake, Kael discovers the ruins of a forgotten temple. Strange glyphs glow faintly beneath the water.',
        chapterNumber: 2,
        votes: { upvotes: 156, downvotes: 8, score: 148 },
        status: 'published',
        isEnding: false,
        pullRequest: { isPR: false },
        version: 2,
        stats: {
          reads: 5230,
          uniqueReaders: 3910,
          completionRate: 89.1,
          engagementScore: 94,
          comments: 41,
          childBranches: 3,
        },
        reportCount: 0,
        isFlagged: false,
        coinPrice: 10,
        isUnlockedByUser: true,
        createdAt: '2025-11-17T10:00:00Z',
        updatedAt: '2025-11-30T12:00:00Z',
        subRows: [
          {
            _id: 'c17',
            slug: 'grandchild-f1',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-f',
            ancestorSlugs: ['root-chapter', 'child-f'],
            depth: 2,
            branchIndex: 1,
            authorId: 'user_16',
            authorName: 'Neil R.',
            title: 'The Water Gate',
            content:
              'A hidden mechanism opens an underwater gate leading into chambers untouched for millennia.',
            chapterNumber: 3,
            votes: { upvotes: 81, downvotes: 2, score: 79 },
            status: 'published',
            isEnding: false,
            pullRequest: { isPR: false },
            version: 1,
            stats: {
              reads: 1920,
              uniqueReaders: 1440,
              completionRate: 82.3,
              engagementScore: 85,
              comments: 16,
              childBranches: 0,
            },
            reportCount: 0,
            isFlagged: false,
            coinPrice: 12,
            isUnlockedByUser: false,
            createdAt: '2025-11-18T08:00:00Z',
            updatedAt: '2025-12-01T09:00:00Z',
          },
          {
            _id: 'c18',
            slug: 'grandchild-f2',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-f',
            ancestorSlugs: ['root-chapter', 'child-f'],
            depth: 2,
            branchIndex: 2,
            authorId: 'user_17',
            authorName: 'Krina P.',
            title: 'The Guardian Fish',
            content:
              'An enormous ancient creature circles Kael, protecting the temple from intruders.',
            chapterNumber: 3,
            votes: { upvotes: 74, downvotes: 4, score: 70 },
            status: 'published',
            isEnding: false,
            pullRequest: { isPR: false },
            version: 1,
            stats: {
              reads: 1580,
              uniqueReaders: 1190,
              completionRate: 74.8,
              engagementScore: 78,
              comments: 12,
              childBranches: 0,
            },
            reportCount: 0,
            isFlagged: false,
            coinPrice: 14,
            isUnlockedByUser: false,
            createdAt: '2025-11-18T11:00:00Z',
            updatedAt: '2025-12-01T14:00:00Z',
          },
          {
            _id: 'c19',
            slug: 'grandchild-f3',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-f',
            ancestorSlugs: ['root-chapter', 'child-f'],
            depth: 2,
            branchIndex: 3,
            authorId: 'user_18',
            authorName: 'Yash T.',
            title: 'Temple Core',
            content:
              'At the center of the temple rests a floating orb containing memories of an ancient civilization.',
            chapterNumber: 3,
            votes: { upvotes: 98, downvotes: 1, score: 97 },
            status: 'pending_approval',
            isEnding: false,
            pullRequest: { isPR: true, status: 'pending' },
            version: 1,
            stats: {
              reads: 1240,
              uniqueReaders: 910,
              completionRate: 91.2,
              engagementScore: 96,
              comments: 20,
              childBranches: 0,
            },
            reportCount: 0,
            isFlagged: false,
            coinPrice: 18,
            isUnlockedByUser: false,
            createdAt: '2025-11-19T15:00:00Z',
            updatedAt: '2025-12-02T12:00:00Z',
          },
        ],
      },
      {
        _id: 'c20',
        slug: 'child-g',
        storySlug: 'the-lost-kingdom',
        parentChapterSlug: 'root-chapter',
        ancestorSlugs: ['root-chapter'],
        depth: 1,
        branchIndex: 7,
        authorId: 'user_19',
        authorName: 'Dev P.',
        title: 'The City of Ash',
        content:
          'Beyond the western cliffs lies a city buried beneath volcanic ash. Kael senses the rune reacting to something beneath the ruins.',
        chapterNumber: 2,
        votes: { upvotes: 133, downvotes: 5, score: 128 },
        status: 'published',
        isEnding: false,
        pullRequest: { isPR: false },
        version: 3,
        stats: {
          reads: 4170,
          uniqueReaders: 3020,
          completionRate: 84.2,
          engagementScore: 89,
          comments: 34,
          childBranches: 2,
        },
        reportCount: 0,
        isFlagged: false,
        coinPrice: 8,
        isUnlockedByUser: true,
        createdAt: '2025-11-20T10:00:00Z',
        updatedAt: '2025-12-03T09:00:00Z',
        subRows: [
          {
            _id: 'c21',
            slug: 'grandchild-g1',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-g',
            ancestorSlugs: ['root-chapter', 'child-g'],
            depth: 2,
            branchIndex: 1,
            authorId: 'user_20',
            authorName: 'Parth M.',
            title: 'Ashen King',
            content:
              'Kael uncovers the tomb of a forgotten king whose crown contains a fragment of the rune.',
            chapterNumber: 3,
            votes: { upvotes: 88, downvotes: 3, score: 85 },
            status: 'published',
            isEnding: false,
            pullRequest: { isPR: false },
            version: 1,
            stats: {
              reads: 1860,
              uniqueReaders: 1390,
              completionRate: 79.5,
              engagementScore: 83,
              comments: 11,
              childBranches: 0,
            },
            reportCount: 0,
            isFlagged: false,
            coinPrice: 12,
            isUnlockedByUser: false,
            createdAt: '2025-11-21T08:00:00Z',
            updatedAt: '2025-12-04T10:00:00Z',
          },
          {
            _id: 'c22',
            slug: 'grandchild-g2',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-g',
            ancestorSlugs: ['root-chapter', 'child-g'],
            depth: 2,
            branchIndex: 2,
            authorId: 'user_21',
            authorName: 'Isha B.',
            title: 'The Buried Machine',
            content:
              'A colossal machine hidden under the city begins to awaken when Kael approaches.',
            chapterNumber: 3,
            votes: { upvotes: 67, downvotes: 2, score: 65 },
            status: 'published',
            isEnding: false,
            pullRequest: { isPR: false },
            version: 1,
            stats: {
              reads: 1410,
              uniqueReaders: 1020,
              completionRate: 72.1,
              engagementScore: 76,
              comments: 9,
              childBranches: 0,
            },
            reportCount: 0,
            isFlagged: false,
            coinPrice: 14,
            isUnlockedByUser: false,
            createdAt: '2025-11-21T12:00:00Z',
            updatedAt: '2025-12-04T15:00:00Z',
          },
        ],
      },
      {
        _id: 'c23',
        slug: 'child-h',
        storySlug: 'the-lost-kingdom',
        parentChapterSlug: 'root-chapter',
        ancestorSlugs: ['root-chapter'],
        depth: 1,
        branchIndex: 8,
        authorId: 'user_22',
        authorName: 'Riya S.',
        title: 'The Sky Fortress',
        content:
          'Floating above the clouds, an ancient fortress drifts silently through the heavens. Kael must find a way aboard.',
        chapterNumber: 2,
        votes: { upvotes: 171, downvotes: 3, score: 168 },
        status: 'published',
        isEnding: false,
        pullRequest: { isPR: false },
        version: 2,
        stats: {
          reads: 6210,
          uniqueReaders: 4710,
          completionRate: 91.3,
          engagementScore: 97,
          comments: 53,
          childBranches: 2,
        },
        reportCount: 0,
        isFlagged: false,
        coinPrice: 15,
        isUnlockedByUser: true,
        createdAt: '2025-11-22T07:00:00Z',
        updatedAt: '2025-12-05T09:00:00Z',
        subRows: [
          {
            _id: 'c24',
            slug: 'grandchild-h1',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-h',
            ancestorSlugs: ['root-chapter', 'child-h'],
            depth: 2,
            branchIndex: 1,
            authorId: 'user_23',
            authorName: 'Vansh K.',
            title: 'Cloud Harbor',
            content:
              'The fortress contains an entire city hidden among the clouds, populated by descendants of ancient explorers.',
            chapterNumber: 3,
            votes: { upvotes: 112, downvotes: 2, score: 110 },
            status: 'published',
            isEnding: false,
            pullRequest: { isPR: false },
            version: 1,
            stats: {
              reads: 2670,
              uniqueReaders: 2020,
              completionRate: 86.4,
              engagementScore: 90,
              comments: 21,
              childBranches: 0,
            },
            reportCount: 0,
            isFlagged: false,
            coinPrice: 18,
            isUnlockedByUser: false,
            createdAt: '2025-11-23T10:00:00Z',
            updatedAt: '2025-12-06T11:00:00Z',
          },
          {
            _id: 'c25',
            slug: 'grandchild-h2',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-h',
            ancestorSlugs: ['root-chapter', 'child-h'],
            depth: 2,
            branchIndex: 2,
            authorId: 'user_24',
            authorName: 'Tanvi R.',
            title: 'Engine of the Sky',
            content:
              'Deep within the fortress, Kael discovers the magical engine keeping the city afloat.',
            chapterNumber: 3,
            votes: { upvotes: 93, downvotes: 1, score: 92 },
            status: 'pending_approval',
            isEnding: false,
            pullRequest: { isPR: true, status: 'pending' },
            version: 1,
            stats: {
              reads: 1550,
              uniqueReaders: 1180,
              completionRate: 88.2,
              engagementScore: 94,
              comments: 15,
              childBranches: 0,
            },
            reportCount: 0,
            isFlagged: false,
            coinPrice: 20,
            isUnlockedByUser: false,
            createdAt: '2025-11-23T15:00:00Z',
            updatedAt: '2025-12-06T16:00:00Z',
          },
        ],
      },
    ],
  },
];
