import type { IChapterTableRow } from './types';

export const MOCK_CURRENT_USER_ID = 'user_1';

// Mock chapters with coin gating, unlock status, full stats
export const MOCK_CHAPTERS_TABLE: IChapterTableRow[] = [
  {
    _id: 'c1',
    slug: 'root-chapter',
    storySlug: 'the-lost-kingdom',
    parentChapterSlug: null,
    ancestorSlugs: [],
    depth: 0,
    branchIndex: 1,
    authorId: 'user_1',
    authorName: 'Dhruv M.',
    title: 'The Beginning of Everything',
    content:
      'In the land of Eldara, a young wanderer named Kael discovers a glowing rune etched into an ancient stone. The rune pulses with a warmth that speaks of forgotten power, and Kael feels an inexplicable pull to follow where it leads.',
    chapterNumber: 1,
    votes: { upvotes: 142, downvotes: 11, score: 131 },
    status: 'published',
    isEnding: false,
    pullRequest: { isPR: false },
    version: 3,
    stats: {
      reads: 4812,
      uniqueReaders: 3201,
      completionRate: 87.4,
      engagementScore: 92,
      comments: 38,
      childBranches: 3,
    },
    reportCount: 0,
    isFlagged: false,
    coinPrice: 0,
    isUnlockedByUser: true,
    createdAt: '2025-11-01T10:00:00Z',
    updatedAt: '2025-11-15T14:22:00Z',
    subRows: [
      {
        _id: 'c2',
        slug: 'child-a',
        storySlug: 'the-lost-kingdom',
        parentChapterSlug: 'root-chapter',
        ancestorSlugs: ['root-chapter'],
        depth: 1,
        branchIndex: 1,
        authorId: 'user_2',
        authorName: 'Aria K.',
        title: 'Into the Eastern Forest',
        content:
          "Kael ventures east into the Thornwood Forest, guided by the rune's faint glow. Ancient trees loom overhead, and the silence is broken only by the distant cry of an unseen creature.",
        chapterNumber: 2,
        votes: { upvotes: 87, downvotes: 5, score: 82 },
        status: 'published',
        isEnding: false,
        pullRequest: { isPR: false },
        version: 2,
        stats: {
          reads: 3104,
          uniqueReaders: 2098,
          completionRate: 79.2,
          engagementScore: 84,
          comments: 21,
          childBranches: 2,
        },
        reportCount: 0,
        isFlagged: false,
        coinPrice: 5,
        isUnlockedByUser: true,
        createdAt: '2025-11-03T12:00:00Z',
        updatedAt: '2025-11-16T09:10:00Z',
        subRows: [
          {
            _id: 'c3',
            slug: 'grandchild-a1',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-a',
            ancestorSlugs: ['root-chapter', 'child-a'],
            depth: 2,
            branchIndex: 1,
            authorId: 'user_3',
            authorName: 'Leo F.',
            title: 'The Glowing Clue',
            content:
              'Kael discovers a mysterious clue beneath an old oak tree — a shard of crystal that mirrors the rune. It shows a vision of a palace swallowed by darkness.',
            chapterNumber: 3,
            votes: { upvotes: 54, downvotes: 3, score: 51 },
            status: 'published',
            isEnding: false,
            pullRequest: { isPR: false },
            version: 1,
            stats: {
              reads: 1920,
              uniqueReaders: 1401,
              completionRate: 68.5,
              engagementScore: 71,
              comments: 9,
              childBranches: 0,
            },
            reportCount: 0,
            isFlagged: false,
            coinPrice: 10,
            isUnlockedByUser: false,
            createdAt: '2025-11-05T08:00:00Z',
            updatedAt: '2025-11-17T11:30:00Z',
          },
          {
            _id: 'c4',
            slug: 'grandchild-a2',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-a',
            ancestorSlugs: ['root-chapter', 'child-a'],
            depth: 2,
            branchIndex: 2,
            authorId: 'user_4',
            authorName: 'Nina P.',
            title: "The Stranger's Warning",
            content:
              'A cloaked figure appears from behind a willow tree, urging Kael to turn back. "The rune is a beacon," the stranger warns. "And something ancient has already seen it."',
            chapterNumber: 3,
            votes: { upvotes: 41, downvotes: 7, score: 34 },
            status: 'pending_approval',
            isEnding: false,
            pullRequest: { isPR: true, status: 'pending' },
            version: 1,
            stats: {
              reads: 980,
              uniqueReaders: 760,
              completionRate: 55.1,
              engagementScore: 58,
              comments: 14,
              childBranches: 0,
            },
            reportCount: 2,
            isFlagged: false,
            coinPrice: 0,
            isUnlockedByUser: true,
            createdAt: '2025-11-06T14:00:00Z',
            updatedAt: '2025-11-18T16:00:00Z',
          },
        ],
      },
      {
        _id: 'c5',
        slug: 'child-b',
        storySlug: 'the-lost-kingdom',
        parentChapterSlug: 'root-chapter',
        ancestorSlugs: ['root-chapter'],
        depth: 1,
        branchIndex: 2,
        authorId: 'user_5',
        authorName: 'Sam W.',
        title: 'The Deserted Village',
        content:
          'Choosing the southern road, Kael arrives at an abandoned village. The homes are intact but lifeless — as if the inhabitants vanished in an instant.',
        chapterNumber: 2,
        votes: { upvotes: 29, downvotes: 12, score: 17 },
        status: 'rejected',
        isEnding: false,
        pullRequest: { isPR: true, status: 'rejected', prId: 'pr_001' },
        version: 1,
        stats: {
          reads: 420,
          uniqueReaders: 310,
          completionRate: 42.0,
          engagementScore: 38,
          comments: 5,
          childBranches: 1,
        },
        reportCount: 3,
        isFlagged: true,
        coinPrice: 0,
        isUnlockedByUser: true,
        createdAt: '2025-11-04T09:30:00Z',
        updatedAt: '2025-11-19T12:00:00Z',
        subRows: [
          {
            _id: 'c6',
            slug: 'grandchild-b1',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-b',
            ancestorSlugs: ['root-chapter', 'child-b'],
            depth: 2,
            branchIndex: 1,
            authorId: 'user_6',
            authorName: 'Priya D.',
            title: 'The Injured Traveler',
            content:
              'Inside a ruined house, Kael finds an injured traveler clutching a tattered map. Before losing consciousness, the traveler whispers, "Follow the constellation of the Serpent."',
            chapterNumber: 3,
            votes: { upvotes: 18, downvotes: 2, score: 16 },
            status: 'published',
            isEnding: false,
            pullRequest: { isPR: false },
            version: 1,
            stats: {
              reads: 310,
              uniqueReaders: 240,
              completionRate: 61.3,
              engagementScore: 62,
              comments: 3,
              childBranches: 0,
            },
            reportCount: 0,
            isFlagged: false,
            coinPrice: 15,
            isUnlockedByUser: false,
            createdAt: '2025-11-08T11:00:00Z',
            updatedAt: '2025-11-20T08:00:00Z',
          },
        ],
      },
      {
        _id: 'c7',
        slug: 'child-c',
        storySlug: 'the-lost-kingdom',
        parentChapterSlug: 'root-chapter',
        ancestorSlugs: ['root-chapter'],
        depth: 1,
        branchIndex: 3,
        authorId: 'user_7',
        authorName: 'Zara O.',
        title: 'The Hidden Cave',
        content:
          'A narrow crevice behind a waterfall leads Kael into a vast cave system. The walls glimmer with bioluminescent moss, and the air hums with ancient energy.',
        chapterNumber: 2,
        votes: { upvotes: 103, downvotes: 4, score: 99 },
        status: 'published',
        isEnding: false,
        pullRequest: { isPR: false },
        version: 2,
        stats: {
          reads: 2760,
          uniqueReaders: 1890,
          completionRate: 83.0,
          engagementScore: 88,
          comments: 29,
          childBranches: 3,
        },
        reportCount: 0,
        isFlagged: false,
        coinPrice: 8,
        isUnlockedByUser: true,
        createdAt: '2025-11-04T16:00:00Z',
        updatedAt: '2025-11-22T10:45:00Z',
        subRows: [
          {
            _id: 'c8',
            slug: 'grandchild-c1',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-c',
            ancestorSlugs: ['root-chapter', 'child-c'],
            depth: 2,
            branchIndex: 1,
            authorId: 'user_8',
            authorName: 'Ben A.',
            title: 'Ancient Carvings',
            content:
              'Kael traces the carvings on the cave wall — a pictographic history of a civilization that once ruled the continent. One carving shows a figure holding the same rune.',
            chapterNumber: 3,
            votes: { upvotes: 12, downvotes: 4, score: 8 },
            status: 'rejected',
            isEnding: false,
            pullRequest: { isPR: true, status: 'rejected' },
            version: 1,
            stats: {
              reads: 210,
              uniqueReaders: 175,
              completionRate: 38.0,
              engagementScore: 35,
              comments: 2,
              childBranches: 0,
            },
            reportCount: 1,
            isFlagged: false,
            coinPrice: 0,
            isUnlockedByUser: true,
            createdAt: '2025-11-09T07:00:00Z',
            updatedAt: '2025-11-21T14:00:00Z',
          },
          {
            _id: 'c9',
            slug: 'grandchild-c2',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-c',
            ancestorSlugs: ['root-chapter', 'child-c'],
            depth: 2,
            branchIndex: 2,
            authorId: 'user_9',
            authorName: 'Maya R.',
            title: 'The Deep Rumble',
            content:
              'The ground shakes. A low, resonant rumble rolls through the cave as if something enormous is stirring far below. Dust cascades from the ceiling. Kael freezes.',
            chapterNumber: 3,
            votes: { upvotes: 78, downvotes: 2, score: 76 },
            status: 'published',
            isEnding: false,
            pullRequest: { isPR: false },
            version: 2,
            stats: {
              reads: 1510,
              uniqueReaders: 1100,
              completionRate: 75.4,
              engagementScore: 80,
              comments: 17,
              childBranches: 0,
            },
            reportCount: 0,
            isFlagged: false,
            coinPrice: 12,
            isUnlockedByUser: false,
            createdAt: '2025-11-10T10:00:00Z',
            updatedAt: '2025-11-23T09:00:00Z',
          },
          {
            _id: 'c10',
            slug: 'grandchild-c3',
            storySlug: 'the-lost-kingdom',
            parentChapterSlug: 'child-c',
            ancestorSlugs: ['root-chapter', 'child-c'],
            depth: 2,
            branchIndex: 3,
            authorId: 'user_1',
            authorName: 'Dhruv M.',
            title: 'Trapped in the Chamber',
            content:
              'The cave entrance collapses behind Kael, sealing him inside a vast hidden chamber. At its center, a glowing altar holds a crystal sphere that shows visions of the future.',
            chapterNumber: 3,
            votes: { upvotes: 64, downvotes: 1, score: 63 },
            status: 'pending_approval',
            isEnding: true,
            pullRequest: { isPR: true, status: 'pending' },
            version: 1,
            stats: {
              reads: 890,
              uniqueReaders: 670,
              completionRate: 90.1,
              engagementScore: 95,
              comments: 11,
              childBranches: 0,
            },
            reportCount: 0,
            isFlagged: false,
            coinPrice: 20,
            isUnlockedByUser: false,
            createdAt: '2025-11-11T15:00:00Z',
            updatedAt: '2025-11-24T11:30:00Z',
          },
        ],
      },
    ],
  },
];
