import type { AnalyticsData } from './analytics.types';

export const mockAnalyticsData: AnalyticsData = {
  overview: {
    totalChapters: 16,
    totalReads: 12500,
    totalUpvotes: 2345,
    upvoteRatio: 94.2,
    totalComments: 890,
    totalBookmarks: 412,
    coinUnlocks: 680,
    unlockedUsersCount: 420,
    chaptersChange: 12.5,
    readsChange: 15.4,
    upvotesChange: 8.2,
    commentsChange: 23.1,
    bookmarksChange: 14.5,
    unlocksChange: 11.8,
  },
  readsOverTime: [
    { date: 'Mon', reads: 1200, uniqueVisitors: 980, upvotes: 210, unlocks: 45 },
    { date: 'Tue', reads: 1800, uniqueVisitors: 1450, upvotes: 340, unlocks: 62 },
    { date: 'Wed', reads: 2200, uniqueVisitors: 1800, upvotes: 410, unlocks: 88 },
    { date: 'Thu', reads: 1900, uniqueVisitors: 1520, upvotes: 380, unlocks: 70 },
    { date: 'Fri', reads: 2400, uniqueVisitors: 1950, upvotes: 520, unlocks: 110 },
    { date: 'Sat', reads: 2800, uniqueVisitors: 2300, upvotes: 610, unlocks: 145 },
    { date: 'Sun', reads: 2600, uniqueVisitors: 2100, upvotes: 570, unlocks: 130 },
  ],
  topChapters: [
    {
      id: '1',
      title: 'The Final Confrontation',
      chapterNumber: 12,
      reads: 2341,
      unlocks: 245,
      upvotes: 420,
      isLocked: true,
      change: 45,
    },
    {
      id: '2',
      title: 'Betrayal at Dawn',
      chapterNumber: 11,
      reads: 1890,
      unlocks: 190,
      upvotes: 350,
      isLocked: true,
      change: 12,
    },
    {
      id: '3',
      title: 'The Awakening',
      chapterNumber: 1,
      reads: 1456,
      unlocks: 0,
      upvotes: 290,
      isLocked: false,
      change: 5,
    },
    {
      id: '4',
      title: 'The Alliance',
      chapterNumber: 8,
      reads: 1234,
      unlocks: 135,
      upvotes: 210,
      isLocked: true,
      change: -3,
    },
    {
      id: '5',
      title: 'Shadows of the Citadel',
      chapterNumber: 5,
      reads: 1102,
      unlocks: 110,
      upvotes: 185,
      isLocked: true,
      change: 8,
    },
  ],

  chapterRetention: [
    { chapterNumber: 1, title: 'The Awakening', readers: 3250, retentionPercentage: 100 },
    { chapterNumber: 2, title: 'Whispering Ruins', readers: 2760, retentionPercentage: 84.9 },
    { chapterNumber: 3, title: 'The Crossroads', readers: 2240, retentionPercentage: 68.9 },
    { chapterNumber: 4, title: 'Shadows of the Citadel', readers: 1820, retentionPercentage: 56.0 },
    { chapterNumber: 5, title: 'The Sealed Vault', readers: 1490, retentionPercentage: 45.8 },
    { chapterNumber: 6, title: 'Echoes of Eternity', readers: 1210, retentionPercentage: 37.2 },
  ],
  contributionStats: {
    totalPRs: 28,
    mergedPRs: 19,
    pendingPRs: 5,
    acceptanceRate: 67.8,
    activeContributors: 14,
    recentPRs: [
      {
        id: 'pr-101',
        title: 'Ch. 13 Draft: The Dragon Sage Emerges',
        author: 'alex_lore',
        status: 'pending',
        date: '2 hours ago',
      },
      {
        id: 'pr-100',
        title: 'Ch. 12 Branch B: Alternative Escape',
        author: 'valkyrie99',
        status: 'merged',
        date: 'Yesterday',
      },
      {
        id: 'pr-99',
        title: 'Ch. 11 Hotfix: Character Dialog Fixes',
        author: 'mythic_writer',
        status: 'merged',
        date: '3 days ago',
      },
      {
        id: 'pr-98',
        title: 'Ch. 10 Extension: Tavern Side Quest',
        author: 'scribe_john',
        status: 'rejected',
        date: '4 days ago',
      },
    ],
  },
  branchingStats: {
    totalBranches: 12,
    activeBranches: 5,
    maxDepth: 8,
    avgReadsPerBranch: 450,
  },
};
