import type { AnalyticsData } from './analytics.types';

export const mockAnalyticsData: AnalyticsData = {
  overview: {
    totalReads: 12500,
    totalVotes: 2345,
    totalComments: 890,
    rating: 4.7,
    newSubscribers: 23,
    readsChange: 15,
    votesChange: 8,
    commentsChange: 23,
    ratingChange: 0.1,
    subscribersChange: 12,
  },
  readsOverTime: [
    { date: 'Mon', reads: 1200, uniqueVisitors: 980 },
    { date: 'Tue', reads: 1800, uniqueVisitors: 1450 },
    { date: 'Wed', reads: 2200, uniqueVisitors: 1800 },
    { date: 'Thu', reads: 1900, uniqueVisitors: 1520 },
    { date: 'Fri', reads: 2400, uniqueVisitors: 1950 },
    { date: 'Sat', reads: 2800, uniqueVisitors: 2300 },
    { date: 'Sun', reads: 2600, uniqueVisitors: 2100 },
  ],
  topChapters: [
    { id: '1', title: 'The Final Confrontation', chapterNumber: 47, reads: 2341, change: 45 },
    { id: '2', title: 'Betrayal at Dawn', chapterNumber: 46, reads: 1890, change: 12 },
    { id: '3', title: 'The Beginning', chapterNumber: 1, reads: 1456, change: 5 },
    { id: '4', title: 'The Alliance', chapterNumber: 45, reads: 1234, change: -3 },
    { id: '5', title: 'Shadows of the Past', chapterNumber: 44, reads: 1102, change: 8 },
  ],
  recentActivity: [
    {
      id: '1',
      type: 'read',
      user: '@fantasy_reader',
      action: 'read',
      target: 'Chapter 47: The Final Confrontation',
      time: '2m ago',
    },
    {
      id: '2',
      type: 'comment',
      user: '@mystery_lover',
      action: 'commented on',
      target: 'Chapter 46: Betrayal at Dawn',
      time: '5m ago',
    },
    {
      id: '3',
      type: 'vote',
      user: '@book_worm',
      action: 'upvoted',
      target: 'Chapter 47',
      time: '12m ago',
    },
    {
      id: '4',
      type: 'subscribe',
      user: '@new_reader',
      action: 'subscribed to your story',
      time: '18m ago',
    },
    {
      id: '5',
      type: 'branch',
      user: '@creative_writer',
      action: 'created a branch from',
      target: 'Chapter 45',
      time: '25m ago',
    },
    {
      id: '6',
      type: 'read',
      user: '@avid_reader',
      action: 'finished reading',
      target: 'Chapter 1-10',
      time: '32m ago',
    },
  ],
  readingProgress: [
    { label: 'Ch. 1-10', value: 3250 },
    { label: 'Ch. 11-25', value: 1850 },
    { label: 'Ch. 26-40', value: 1200 },
    { label: 'Ch. 41-47', value: 750 },
    { label: 'Caught Up', value: 450 },
  ],
  engagementFunnel: [
    { label: 'Visited Story Page', value: 5000, percentage: 100 },
    { label: 'Started Ch. 1', value: 4100, percentage: 82 },
    { label: 'Finished Ch. 1', value: 3250, percentage: 65 },
    { label: 'Read Ch. 5+', value: 2250, percentage: 45 },
    { label: 'Read Ch. 20+', value: 1400, percentage: 28 },
    { label: 'Caught Up (Ch.47)', value: 750, percentage: 15 },
  ],
};
